tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
cask_args appdir: "/Applications"

brew "gawk"
brew "gpg"
brew "mas"
brew "neovim"
brew "telnet"
brew "tmux"
brew "tree"
brew "coreutils"

cask "1password"
cask "adobe-creative-cloud"
cask "alfred"
cask "android-studio"
cask "bettertouchtool"
cask "docker"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "kap"
cask "kindle"
cask "karabiner-elements"
cask "ngrok"
cask "parallels"
cask "slack"
cask "sequel-pro"
cask "virtualbox"
cask "visual-studio-code"
cask "zoom"

mas "LanSca", id: 472226235
mas "WiFi Explorer", id: 494803304
mas "Medis2", id: 1579200037
